### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cubicbyte** [yofukashino/PremiumScreenShare#11]
Hi, after install, you can't select any of the premium quality options

**Comment by yofukashino** [comment]
seems to work. maybe update?

**Comment by cubicbyte** [comment]
Everything's in the latest version, I can give the steps to reproduce

1. Install latest discord + replugged installer from the official site
2. Put the latest release .asar file to the plugins dir
3. Restart discord (optional)

After that, the interface does not change at all and the quality options are locked accordingly.

Maybe it's because you're using some other replugged build?

**Comment by yofukashino** [comment]
does the replugged settings show up in discord settings?

**Comment by cubicbyte** [comment]
Yes, they do

**Comment by yofukashino** [comment]
check if plugin is enabled also for any errors in console. ctrl+shift+i prolly

**Comment by cubicbyte** [comment]
No errors in console and plugin is enabled as well

Here's console output so you can check yourself
[discord.log](https://github.com/user-attachments/files/17335380/discord.log)

![image](https://github.com/user-attachments/assets/c3b6b9b9-36d9-47f6-843d-a1a56f609399)
![image](https://github.com/user-attachments/assets/80c5ae36-80b7-466f-8e66-1685a1d906ca)

**Comment by yofukashino** [comment]
i didnt ask for the logs but any errors in particular. they are in red. 

also on stable it works for me so I installed discord-development with different account to test, still works

**Comment by yofukashino** [comment]
wait latest verison of plugin is 1.2.4

**Comment by cubicbyte** [comment]
Okay, I reinstalled .asar from the latest release and now it's version 1.2.4. Before me and my friend did exactly the same thing so I don't know how it is, lol

But on the latest version it still doesn't work but this time there are already errors in the console. I deleted old plugin version settings if anything

## After startup
![изображение](https://github.com/user-attachments/assets/3ced5858-ffc4-4bdc-b5f4-6e757f28320e)

## After plugin reload
![изображение](https://github.com/user-attachments/assets/9c73e81c-1cc4-4e46-9d44-239ca3ecdbc2)

Still no premium options after that, alas

**Comment by yofukashino** [comment]
maybe conflict with other plugins?

**Comment by yofukashino** [comment]
also please send version info off your discord

at bottom on settings sidebar
this: ![image](https://github.com/user-attachments/assets/f537e603-3473-4b6a-af1c-7dd3953b0833)

**Comment by cubicbyte** [comment]
I have no other plugins, your is the most useful imo

![изображение](https://github.com/user-attachments/assets/053c45ec-5ec1-4f6f-863e-3aaabe47c7db)

**Comment by yofukashino** [comment]
honestly i cant replicate the issue

**Comment by cubicbyte** [comment]
Yo, I found what's the issue

This plugin doesn't support non-English interface. Actually I've checked if this is the case before but forgot to reload the plugin after the change

also the error is in this line:
```javascript
c.ApplicationStreamFPSButtonsWithSuffixLabel = Object.entries(a.ApplicationStreamingOption).find( ([t,e]) => Array.isArray(e) && e.some(n => n.label == "15 FPS"))[0],
```

**Comment by yofukashino** [comment]
oki thanks, will make it support other languages, dumb me  :D
