### ISSUE TITLE
Input custom FPS values?

### ISSUE THREAD

**Issue by sylviiu** [yofukashino/PremiumScreenShare#3]
hleo helo!

recently moved from BD to replugged because i saw this plugin (i used a similar one on BD), and can't seem to choose anything between 60 & 120FPS (i usually screenshare @ 90)

would it be possible to input our own values for FPS?

**Comment by Stoutscientist** [comment]
You can go to the plugin settings and change that, but still it would be awesome for an option to input our own values!

**Comment by yofukashino** [comment]
you can use console for that

**Comment by yofukashino** [comment]
closing this due to lack of response

**Comment by sylviiu** [comment]
wanted to circle back to this -- i wanted to create a fork of this to allow custom FPS values; would you be against a pull request for it?

the idea i have would be to use something like a `TextInput` while (somehow?) providing the preset options, allow the user to type in their own value, and get the FPS value just by parsing it as an integer instead of requiring it be a predefined value.

**Comment by yofukashino** [comment]
its like inviting people to crash their client to me. if they know what they are doing, they better use console

**Comment by sylviiu** [comment]
that's entirely fair, nevermind then lol
