### ISSUE TITLE
Not working after discord update

### ISSUE THREAD

**Issue by cubicbyte** [yofukashino/PremiumScreenShare#4]
Hi! After the latest discord updates, it stopped working and crashes in the voice channel

**Comment by yofukashino** [comment]
will be fixed soon already working on it

**Comment by Deadzulu** [comment]
balls

**Comment by yofukashino** [comment]
new update will be relased when https://github.com/replugged-org/replugged/pull/520 gets merged

**Comment by yofukashino** [comment]
made the fix and its working so far for me

**Comment by yofukashino** [comment]
meh i release after commenting out the thing that requires it
