### ISSUE TITLE
This Premium is Purely Visual

### ISSUE THREAD

**Issue by Question333** [yofukashino/PremiumScreenShare#5]
I've examined how much data is being transmitted when using different broadcasting modes. In the standard 720p mode, I'm sending approximately 4.5 Mbps, but in all other modes like 1080p, 1440p, and higher, it still sends around 4.5 Mbps, and in some cases, it even decreases, for example, if I enable 60 frames, the speed drops to 1 Mbps. I also checked my stream from another device, and the streaming quality remained at 720p, even though it indicates that it's broadcasting in 1080p and other modes. I have a 2K monitor, so I should be able to stream in 2K.

**Comment by cubicbyte** [comment]
Dunno, I can say that increased fps (120+) works for sure. About increased resolution - haven't tested it

**Comment by Question333** [comment]
> Dunno, I can say that increased fps (120+) works for sure. About increased resolution - haven't tested it

Can you check the task manager for your upload speed in Mbps at 30 and 120 frames per second? I specifically activated Discord Nitro and checked that on the regular client at 60 frames per second, or at 1080p resolution, the upload speed is about 10 Mbps. However, when using the plugin, the upload speed does not change and remains at a maximum of 5 Mbps.

**Comment by cubicbyte** [comment]
Just tested it

If without plugin but with nitro, the maximum available quality (1080@60) requires ~7.5 mbps of network

If using the plugin with/without nitro, the network speed is under 7 mbps, at any resolution/frame rate. That means at critical values, like 1080@144, heavy artifacts may appear. So I recommend to use 1080@120 / 720@120+ quality

**Comment by yofukashino** [comment]
![image](https://github.com/Tharki-God/PremiumScreenShare/assets/73281112/1cc26db5-dea3-40e9-bb13-466724b2fbaf)
are you sure about that? streaming at 4k 60 fps...

**Comment by yofukashino** [comment]
and yes its ip leak kekw (fr fr)

**Comment by yofukashino** [comment]
done in new update
